In [95]:
import numpy as np
import scipy.linalg as sp

# Exercício 1


## 1.1)
Escrevemos uma rotina que resolva sistemas de equações lineares pelo método de Gauss com pivotage parcial.

In [98]:
def gauss_solve(A, v):
    A, v = np.array(A, float), np.array(v, float)
    n = len(A)
    epsilon = 1e-14
    index = np.arange(n)
    for i in range(n):
        d = A[i, i]
        print("d" , d )
        if d > epsilon:
            A[index[i], i:] /= d
        elif i < n - 1:
            i_max = np.argmax(np.absolute(A[i + 1:,i])) + i + 1 #erro
            index[i], index[i_max] = index[i_max], index[i]
            d = A[index[i], i]
            A[index[i], i:] /= d
        v[i] /= d
        print(A)
        print(index)
        for j in range(i + 1, n):
            m = A[index[j], i]
            if m > epsilon:
                A[index[j],:] -= A[index[i],:] * m
                v[index[j]] -= v[index[i]] * m
    #x = np.zeros(n)
    #x[-1] = v[-1]
    #for i in range(2, n + 1):
    #    x[-ind] = v[-ind] - (A[-ind, -i+1:]*x[-ind+1:]).sum()
    return A

#------------------------------------------------------------------------
A = np.array([
    [0, 2, 2],
    [2, 1, 1],
    [5, 3, 2]
])
v = np.array([1, 1, 1])
gauss_solve(A, v)

d 0.0
[[0.  2.  2. ]
 [2.  1.  1. ]
 [1.  0.6 0.4]]
[2 1 0]
d -0.19999999999999996
[[ 0.   1.   1. ]
 [ 0.  -0.2  0.2]
 [ 1.   0.6  0.4]]
[2 0 1]
d 0.4
[[ 0.   1.   1. ]
 [ 0.  -0.2  0.5]
 [ 1.   0.6  0.4]]
[2 0 1]


array([ 0.25, -1.25,  1.75])

In [97]:
print(A[1:, 0])

[2 5]


# 1.2)
Temos o seguinte sistema de equações:

$m_{i} \frac{d^{2} X_{i}}{d t^{2}}=-k_{i}\left(X_{i}-X_{i-1}\right)+k_{i+1}\left(X_{i+1}-X_{i}\right)$

sendo $X_o = 0$ e $X_{N + 1} = L$.

A condição de equilíbrio implica $\frac{d^{2} X_{i}}{d t^{2}} = 0$.

De onde obtemos o sistema de equações:

$ -k_{i}\left(X_{i}-X_{i-1}\right)+k_{i+1}\left(X_{i+1}-X_{i}\right) = 0 $.

Concluímos imediatamente que a matrix será uma tridiagonal, sendo que cada massa so interage com osbseus vizinhos.

In [100]:
def solve_tridiag(A, v):
    n = len(A)
    x = np.empty(n, float)
    for i in range(n - 1):
        d = A[i, i]
        A[i, i+1] /= d
        v[i] /= d
        A[i+1, i+1] -= A[i+1, i] * A[i, i+1]
        v[i+1] -= A[i+1, i] * v[i]
    v[n-1] /= A[n-1, n-1]
    x[n-1] = v[n-1]
    for i in range(n-2, -1, -1):
        x[i] = v[i] - A[i, i+1] * x[i+1]
    return x

A = np.array([
    [1, 2, 0, 0],
    [3, 1, 3, 0],
    [0, 1, 1, 1],
    [0, 0, 2, 1]
], float)
    
v = np.array([1, 1, 1, 1], float)

print(solve_tridiag(A, v))
print(sp.solve(A, v))

[-1.  1.  1. -1.]
[ 0.48791667  0.25604167 -0.36076389  1.11388889]


*i)* Se as massa são iguais, temos o sistema:

$\left(X_{i}-X_{i-1}\right)+\left(X_{i+1}-X_{i}\right) = 0$.